# Generated by Django 5.0.4 on 2024-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_admin', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
