# Generated by Django 5.0.4 on 2024-04-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0002_admins_delete_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admins',
            table='admins',
        ),
    ]
